version: '3'

services:
  sql:
    image: mysql
    container_name: sql
    restart: always
    networks:
      - mynet
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password    
    command: 
      --default-authentication-plugin=mysql_native_password
    ports: 
      - 3306:3306
      - 33060:33060
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - sql
    networks:
      - mynet
 

networks:
  mynet:
    driver: bridge
