global:
  scrape_interval:     5s
  scrape_timeout:      3s
  evaluation_interval: 5s
  external_labels:
        monitor: 'my-monitor'
scrape_configs:
    - job_name: 'mysql-exporter'
      static_configs:
          - targets: ['mysql-exporter:9104']